# Generated by Django 2.0.7 on 2018-07-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='static\\face\\default.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='没有昵称', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='qqnumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='usrgroup',
            field=models.IntegerField(default=0),
        ),
    ]
