# Generated by Django 2.0.7 on 2018-07-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0003_auto_20180709_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_time',
            field=models.IntegerField(default=0),
        ),
    ]
