# Generated by Django 2.0.7 on 2018-07-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0004_user_register_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=1024)),
                ('coordinate', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=1024)),
                ('detail', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=100)),
                ('progress', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('picture', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='DeclareAnimals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declare_time', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=100)),
                ('binding', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=64)),
                ('feature', models.CharField(max_length=64)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeclareResidences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declare_time', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=100)),
                ('coordinate', models.CharField(max_length=64)),
                ('area', models.CharField(max_length=64)),
                ('concept', models.CharField(max_length=1024)),
                ('plan', models.CharField(max_length=1024)),
                ('detail', models.CharField(max_length=2048)),
                ('perspective', models.CharField(max_length=1024)),
                ('predict_start_time', models.IntegerField(default=0)),
                ('predict_end_time', models.IntegerField(default=0)),
                ('actually_end_time', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Key',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='static\\face\\default.jpg', max_length=1024),
        ),
    ]
