# Generated by Django 2.0.7 on 2018-07-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0006_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.CharField(default='%default%', max_length=2048),
        ),
    ]
