# Generated by Django 2.0.7 on 2018-07-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0007_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='declareresidences',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='declareresidences',
            name='area',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='declareresidences',
            name='concept',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='declareresidences',
            name='coordinate',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='declareresidences',
            name='detail',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='declareresidences',
            name='perspective',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='declareresidences',
            name='plan',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='declareresidences',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
