# Generated by Django 2.0.7 on 2018-07-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0008_auto_20180712_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='declareresidences',
            name='summary',
            field=models.CharField(default='', max_length=128),
        ),
    ]
