# Generated by Django 2.0.7 on 2018-07-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0009_declareresidences_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='declareresidences',
            name='english_name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
