# Generated by Django 2.0.7 on 2018-07-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0011_auto_20180716_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
