# Generated by Django 2.0.7 on 2018-07-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0012_announcement_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='C:\\Users\\hji20\\PycharmProjects\\QieGaoWorld\\static\\media\\face\\default.jpg', max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.CharField(default='%default%police_cases_watch%police_cases_add%declaration_animals%declaration_buildings%declaration_watch% ', max_length=2048),
        ),
    ]
