# Generated by Django 2.0.7 on 2018-08-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0017_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='Logs',
        ),
    ]
