# Generated by Django 2.0.7 on 2018-09-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0018_auto_20180825_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(max_length=2)),
                ('url', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('parent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wenjuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dry', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('list', models.IntegerField(default=0)),
                ('create_time', models.TimeField()),
                ('update_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
