# Generated by Django 2.0.7 on 2018-09-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0020_auto_20180904_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wenjuan',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='wenjuan',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
