# Generated by Django 2.0.7 on 2018-09-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0021_auto_20180904_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wenjuan',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='wenjuan',
            name='update_time',
        ),
    ]
