# Generated by Django 2.0.7 on 2018-09-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0022_auto_20180904_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wenjuan',
            new_name='Problem',
        ),
    ]
