# Generated by Django 2.0.7 on 2018-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0024_probleminfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.IntegerField(),
        ),
    ]
