# Generated by Django 2.0.7 on 2018-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0025_auto_20180904_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleminfo',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
