# Generated by Django 2.0.7 on 2018-09-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0026_probleminfo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WenjuanLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('problem_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
