# Generated by Django 2.0.7 on 2018-09-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QieGaoWorld', '0028_conf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkullCustomize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content', models.TextField()),
                ('number', models.IntegerField()),
                ('status', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
